src/objects/CC_Integration_Service__mdt.object
<CustomObject>
    <fields>
        <fullName>CC_Endpoint__c</fullName>
        <label>Endpoint</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Method__c</fullName>
        <label>Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CC_Mock__c</fullName>
        <label>Mock</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>CC_Retrieve_Mock__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Retrieve Mock</label>
        <type>Checkbox</type>
    </fields>
    <label>Integration Service</label>
    <pluralLabel>Integrations Services</pluralLabel>
</CustomObject>

src/classes/CC_Integration.cls
/*
* @description CC_Integration integration engine class
* @author Ismael
* @version 1.0
*/
public with sharing class CC_Integration {

    public static HTTPResponse callout(String integrationDevelopName, String body, String queryParam){
        CC_Integration_Service__mdt integrationConfig = [SELECT CC_Endpoint__c, CC_Mock__c, CC_Retrieve_Mock__c, DeveloperName FROM CC_Integration_Service__mdt WHERE DeveloperName = :integrationDevelopName LIMIT 1];
        HttpRequest httpReq = CC_Authentication.applySecurity();
        HTTPResponse res = null;
        if(integrationConfig.CC_Retrieve_Mock__c){
            res = new HTTPResponse();
            res.setBody(integrationConfig.CC_Mock__c);
        }else{
            httpReq.setBody(body);
            httpReq.setMethod(integrationConfig.CC_Method__c);
            httpReq.setEndpoint(integrationConfig.CC_Endpoint__c + queryParam);

            Http http = new Http();
            res = http.send(httpReq);
        }

        return res;

    }

}